version: '3.9'

services:
  php:
    container_name: distance_game_php
    build: docker/php
    volumes:
      - ./../application:/var/www:cached

  node:
    container_name: distance_game_node
    build: docker/node
    volumes:
      - ./../application:/distance_game:cached
    tty: true

  nginx:
    image: nginx
    container_name: distance_game_nginx
    ports:
      - 80:80
    volumes:
      - ./../application:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
      - node

  mysql:
    platform: linux/amd64
    build: docker/mysql
    container_name: distance_game_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: distance_game
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql:cached
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d:cached
    ports:
      - 3306:3306

volumes:
  mysql: